// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * DateRange
 */
export type DateRange = {
    /**
     * Start Date
     */
    start_date: string;
    /**
     * End Date
     */
    end_date: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * Reservation
 */
export type Reservation = {
    /**
     * Dock Id
     */
    dock_id: string;
    /**
     * Reserved By
     */
    reserved_by: string;
    /**
     * Vessel Size
     */
    vessel_size: number;
    vessel_metric?: SizeMetric;
    date_range: DateRange;
};

/**
 * SizeMetric
 */
export type SizeMetric = 'ft' | 'in' | 'm';

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type CreateReservationCreateReservationPostData = {
    body: Reservation;
    path?: never;
    query?: never;
    url: '/create_reservation';
};

export type CreateReservationCreateReservationPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateReservationCreateReservationPostError = CreateReservationCreateReservationPostErrors[keyof CreateReservationCreateReservationPostErrors];

export type CreateReservationCreateReservationPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetCurrentReservationsCurrentReservationsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/current_reservations';
};

export type GetCurrentReservationsCurrentReservationsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
